version: '3'

services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "80:80"

  test:
    hostname: test
    build:
      context: ./tests
      dockerfile: Dockerfile
